// AeroFlow 360 - Aviation Operations Data Store
// Tailored for BBA Aviation Management - Smart Airport Turnaround Automation

window.AERO_DATA = {
  airport: {
    code: "CJB",
    icao: "VOCB",
    name: "Coimbatore International Airport",
    timezone: "IST (UTC+05:30)",
    aoccCommand: "AOCC-Central Control Unit #4",
    operationalStatus: "NORMAL / HIGH DENSITY",
    activeRunway: "RWY 05/23 (3,048 m)",
    weather: {
      temp: "29°C",
      condition: "Clear Skies / Visibility 9000m",
      wind: "090° at 08 kts",
      qnh: "1012 hPa"
    }
  },

  kpis: {
    otpRate: 94.6, // On-Time Performance %
    avgTatMins: 28.4, // Average Turnaround Time in mins (Target: 35m)
    dailyTurnarounds: 48,
    activeDelaysCount: 1,
    costAvoidedTodayLakhs: 8.42,
    gseUtilizationRate: 88.5
  },

  gates: [
    { id: "G1", name: "Gate G1", type: "Aerobridge / Contact", status: "Available", flightId: null, distanceMeters: 120 },
    { id: "G2", name: "Gate G2", type: "Aerobridge / Contact", status: "Occupied", flightId: "FL-003", distanceMeters: 150 },
    { id: "G3", name: "Gate G3", type: "Aerobridge / Contact", status: "Turnaround In Progress", flightId: "FL-001", distanceMeters: 180 },
    { id: "G4", name: "Gate G4", type: "Remote Bay / Bus", status: "Reserved", flightId: "FL-005", distanceMeters: 450 },
    { id: "G5", name: "Gate G5", type: "Aerobridge / Contact", status: "SLA Warning", flightId: "FL-002", distanceMeters: 220 },
    { id: "G6", name: "Gate G6", type: "Remote Bay / Bus", status: "Available", flightId: null, distanceMeters: 500 },
    { id: "G7", name: "Gate G7", type: "Remote Bay / Prop", status: "Pushback Ready", flightId: "FL-004", distanceMeters: 380 },
    { id: "G8", name: "Gate G8", type: "Cargo & Standby", status: "Maintenance", flightId: null, distanceMeters: 620 }
  ],

  flights: [
    {
      id: "FL-001",
      flightNo: "6E 204",
      airline: "IndiGo Airlines",
      airlineCode: "6E",
      logoColor: "#004085",
      accentColor: "#0d6efd",
      aircraft: "Airbus A320neo",
      registration: "VT-IZH",
      paxCapacity: 186,
      paxInbound: 174,
      paxOutbound: 182,
      origin: "DEL (New Delhi)",
      destination: "MAA (Chennai)",
      gate: "G3",
      bayType: "Contact Stand (Aerobridge 3)",
      sta: "14:15",
      eta: "14:12",
      blockIn: "14:14",
      std: "14:50",
      targetTatMins: 35,
      elapsedMins: 19,
      status: "In Progress",
      fuelRequiredKg: 4200,
      cargoBagsIn: 138,
      cargoBagsOut: 145,
      cateringMealTrays: 160,
      turnaroundHealth: "Optimal", // Optimal, Caution, Critical
      delayReason: null,
      delayCode: null,
      milestones: [
        {
          id: "m1",
          code: "CHOCKS_DEBOARD",
          name: "Chocks On & Passenger Deboarding",
          category: "Ramp & Terminal",
          team: "Ramp Marshaller & Cabin Crew",
          icon: "🛬",
          startOffset: 0,
          duration: 5,
          status: "Completed",
          completedAt: "14:19",
          actualDuration: 5,
          slaTargetMins: 5,
          criticalPath: true,
          digitalEvidence: "Chocks placed VT-IZH @ 14:14. Deboarding finished 14:19 (174 Pax).",
          operator: "Ramp Officer R. Karthik (EMP-8821)"
        },
        {
          id: "m2",
          code: "BAGGAGE_OFFLOAD",
          name: "Inbound Baggage Offload & Belt Delivery",
          category: "Ground Handling",
          team: "Ramp Ground Crew - Squad Alpha",
          icon: "🧳",
          startOffset: 3,
          duration: 9,
          status: "Completed",
          completedAt: "14:24",
          actualDuration: 8,
          slaTargetMins: 9,
          criticalPath: true,
          digitalEvidence: "138 bags offloaded to Belt 2. First bag 14:18, Last bag 14:24.",
          operator: "Ramp Lead M. Suresh (EMP-4109)"
        },
        {
          id: "m3",
          code: "CABIN_CLEANING",
          name: "Cabin Grooming & Security Inspection",
          category: "Grooming & Safety",
          team: "SkyClean Services Squad B",
          icon: "✨",
          startOffset: 8,
          duration: 12,
          status: "Completed",
          completedAt: "14:31",
          actualDuration: 11,
          slaTargetMins: 12,
          criticalPath: true,
          digitalEvidence: "Deep vacuum, tray sanitize, 30-row security search cleared.",
          operator: "Grooming Supervisor J. Deepa (EMP-3120)"
        },
        {
          id: "m4",
          code: "REFUELING",
          name: "ATF Aviation Turbine Fueling & Digital Slip",
          category: "Fuel Logistics",
          team: "IOCL Aviation Bowser Team (FB-01)",
          icon: "⛽",
          startOffset: 10,
          duration: 14,
          status: "In-Progress",
          progressPct: 75,
          slaTargetMins: 14,
          criticalPath: true,
          digitalEvidence: "3,150 / 4,200 kg pumped. Density 0.795 g/cm³ verified.",
          operator: "Fueling Tech V. Balan (EMP-7714)"
        },
        {
          id: "m5",
          code: "CATERING",
          name: "In-flight Catering Replenishment",
          category: "Commissary",
          team: "TajSATS Highloader Logistics (CAT-01)",
          icon: "🥪",
          startOffset: 12,
          duration: 13,
          status: "In-Progress",
          progressPct: 60,
          slaTargetMins: 13,
          criticalPath: false,
          digitalEvidence: "160 hot meal crates & 4 dry bar trollies loading.",
          operator: "Catering Head P. Arun (EMP-5491)"
        },
        {
          id: "m6",
          code: "WATER_LAVATORY",
          name: "Potable Water & Lavatory Ground Servicing",
          category: "Utility Servicing",
          team: "Airport Ground Utility Crew (UTIL-02)",
          icon: "🚰",
          startOffset: 15,
          duration: 11,
          status: "In-Progress",
          progressPct: 50,
          slaTargetMins: 11,
          criticalPath: false,
          digitalEvidence: "Potable water 100% full, rear lavatory waste purged.",
          operator: "Utility Tech S. Ravi (EMP-6022)"
        },
        {
          id: "m7",
          code: "BAGGAGE_LOADING",
          name: "Outbound Baggage Loading & Trim Sheet",
          category: "Load & Balance",
          team: "Load Control & Ramp Handling",
          icon: "📦",
          startOffset: 20,
          duration: 10,
          status: "Pending",
          slaTargetMins: 10,
          criticalPath: true,
          digitalEvidence: "145 outbound bags staged at Make-up Area Bay 3.",
          operator: "Load Controller K. Narendran (EMP-1190)"
        },
        {
          id: "m8",
          code: "BOARDING_PUSHBACK",
          name: "Pax Boarding, Doors Armed & Pushback Tug",
          category: "Flight Operations",
          team: "Gate Team & Pushback Tug Driver (TUG-01)",
          icon: "🛫",
          startOffset: 25,
          duration: 10,
          status: "Pending",
          slaTargetMins: 10,
          criticalPath: true,
          digitalEvidence: "Boarding Gate G3 scanner active. Standby for final pax call.",
          operator: "Gate Manager T. Meena (EMP-9201)"
        }
      ]
    },

    {
      id: "FL-002",
      flightNo: "AI 508",
      airline: "Air India",
      airlineCode: "AI",
      logoColor: "#dc3545",
      accentColor: "#e63946",
      aircraft: "Airbus A321",
      registration: "VT-PPB",
      paxCapacity: 192,
      paxInbound: 180,
      paxOutbound: 188,
      origin: "BOM (Mumbai)",
      destination: "BLR (Bengaluru)",
      gate: "G5",
      bayType: "Contact Stand (Aerobridge 5)",
      sta: "14:05",
      eta: "14:02",
      blockIn: "14:04",
      std: "14:45",
      targetTatMins: 40,
      elapsedMins: 29,
      status: "SLA Warning",
      fuelRequiredKg: 5100,
      cargoBagsIn: 162,
      cargoBagsOut: 170,
      cateringMealTrays: 180,
      turnaroundHealth: "Critical",
      delayReason: "Catering Commissary Highloader Hydraulic Pressure Drop",
      delayCode: "34 - In-flight Catering Equipment Delay",
      milestones: [
        {
          id: "m1",
          code: "CHOCKS_DEBOARD",
          name: "Chocks On & Passenger Deboarding",
          team: "Ramp Marshaller & Cabin Crew",
          icon: "🛬",
          startOffset: 0,
          duration: 6,
          status: "Completed",
          completedAt: "14:10",
          actualDuration: 6,
          slaTargetMins: 6,
          criticalPath: true,
          digitalEvidence: "Deboarding completed on schedule.",
          operator: "Ramp Lead N. Anand"
        },
        {
          id: "m2",
          code: "BAGGAGE_OFFLOAD",
          name: "Inbound Baggage Offload & Delivery",
          team: "Ground Handling Squad Charlie",
          icon: "🧳",
          startOffset: 4,
          duration: 10,
          status: "Completed",
          completedAt: "14:15",
          actualDuration: 9,
          slaTargetMins: 10,
          criticalPath: true,
          digitalEvidence: "162 bags offloaded.",
          operator: "Ramp Tech G. Mohan"
        },
        {
          id: "m3",
          code: "CABIN_CLEANING",
          name: "Cabin Grooming & Security Inspection",
          team: "SkyClean Services Squad A",
          icon: "✨",
          startOffset: 9,
          duration: 12,
          status: "Completed",
          completedAt: "14:22",
          actualDuration: 12,
          slaTargetMins: 12,
          criticalPath: true,
          digitalEvidence: "Cabin sanitization signed off.",
          operator: "Supervisor K. Lakshmi"
        },
        {
          id: "m4",
          code: "REFUELING",
          name: "ATF Refueling & Digital Fuel Slip",
          team: "IOCL Aviation Bowser (FB-02)",
          icon: "⛽",
          startOffset: 12,
          duration: 15,
          status: "Completed",
          completedAt: "14:28",
          actualDuration: 14,
          slaTargetMins: 15,
          criticalPath: true,
          digitalEvidence: "5,100 kg uploaded successfully.",
          operator: "Fueling Tech D. Victor"
        },
        {
          id: "m5",
          code: "CATERING",
          name: "In-flight Catering Replenishment",
          team: "SkyGourmet Highloader (CAT-02)",
          icon: "🥪",
          startOffset: 14,
          duration: 12,
          status: "Delayed",
          progressPct: 40,
          slaTargetMins: 12,
          criticalPath: true,
          delayMinutes: 6,
          digitalEvidence: "WARNING: Highloader CAT-02 hydraulic valve jammed. Backup CAT-01 requested.",
          operator: "Catering Officer S. Dinesh"
        },
        {
          id: "m6",
          code: "WATER_LAVATORY",
          name: "Potable Water & Lavatory Servicing",
          team: "Utility Squad",
          icon: "🚰",
          startOffset: 16,
          duration: 10,
          status: "Completed",
          completedAt: "14:26",
          actualDuration: 10,
          slaTargetMins: 10,
          criticalPath: false,
          digitalEvidence: "Water serviced 100%.",
          operator: "Utility Tech R. Prasad"
        },
        {
          id: "m7",
          code: "BAGGAGE_LOADING",
          name: "Outbound Baggage Loading & Trim Sheet",
          team: "Ramp Cargo Crew",
          icon: "📦",
          startOffset: 22,
          duration: 10,
          status: "In-Progress",
          progressPct: 80,
          slaTargetMins: 10,
          criticalPath: true,
          digitalEvidence: "135/170 bags loaded into Aft/Fwd cargo holds.",
          operator: "Load Controller H. Vignesh"
        },
        {
          id: "m8",
          code: "BOARDING_PUSHBACK",
          name: "Pax Boarding, Doors Armed & Pushback",
          team: "Gate Team & Pushback Tug Driver (TUG-02)",
          icon: "🛫",
          startOffset: 28,
          duration: 12,
          status: "In-Progress",
          progressPct: 35,
          slaTargetMins: 12,
          criticalPath: true,
          digitalEvidence: "Boarding stalled at row 15 due to galley catering hold.",
          operator: "Gate Manager S. Kavitha"
        }
      ]
    },

    {
      id: "FL-003",
      flightNo: "QP 1102",
      airline: "Akasa Air",
      airlineCode: "QP",
      logoColor: "#fd7e14",
      accentColor: "#ff922b",
      aircraft: "Boeing 737 MAX 8",
      registration: "VT-YAA",
      paxCapacity: 189,
      paxInbound: 168,
      paxOutbound: 175,
      origin: "HYD (Hyderabad)",
      destination: "COK (Kochi)",
      gate: "G2",
      bayType: "Contact Stand (Aerobridge 2)",
      sta: "14:25",
      eta: "14:22",
      blockIn: "14:24",
      std: "15:05",
      targetTatMins: 40,
      elapsedMins: 8,
      status: "In Progress",
      fuelRequiredKg: 3800,
      cargoBagsIn: 122,
      cargoBagsOut: 130,
      cateringMealTrays: 110,
      turnaroundHealth: "Optimal",
      delayReason: null,
      delayCode: null,
      milestones: [
        {
          id: "m1",
          code: "CHOCKS_DEBOARD",
          name: "Chocks On & Passenger Deboarding",
          team: "Ramp Marshaller & Cabin Crew",
          icon: "🛬",
          startOffset: 0,
          duration: 6,
          status: "Completed",
          completedAt: "14:30",
          actualDuration: 6,
          slaTargetMins: 6,
          criticalPath: true,
          digitalEvidence: "Deboarding completed smoothly.",
          operator: "Ramp Lead K. Balaji"
        },
        {
          id: "m2",
          code: "BAGGAGE_OFFLOAD",
          name: "Inbound Baggage Offload & Delivery",
          team: "Ground Handling Squad Alpha",
          icon: "🧳",
          startOffset: 4,
          duration: 9,
          status: "In-Progress",
          progressPct: 70,
          slaTargetMins: 9,
          criticalPath: true,
          digitalEvidence: "Offloading bulk cargo hold 1.",
          operator: "Ramp Tech P. Manoj"
        },
        {
          id: "m3",
          code: "CABIN_CLEANING",
          name: "Cabin Grooming & Security Inspection",
          team: "SkyClean Services Squad C",
          icon: "✨",
          startOffset: 8,
          duration: 12,
          status: "In-Progress",
          progressPct: 20,
          slaTargetMins: 12,
          criticalPath: true,
          digitalEvidence: "Cleaning crew boarded row 1-32.",
          operator: "Supervisor A. Shalini"
        },
        {
          id: "m4",
          code: "REFUELING",
          name: "ATF Refueling & Digital Fuel Slip",
          team: "IOCL Aviation (FB-01)",
          icon: "⛽",
          startOffset: 10,
          duration: 14,
          status: "Pending",
          slaTargetMins: 14,
          criticalPath: true,
          digitalEvidence: "Awaiting grounding clip confirmation.",
          operator: "Fueling Tech V. Balan"
        },
        {
          id: "m5",
          code: "CATERING",
          name: "In-flight Catering Replenishment",
          team: "TajSATS (CAT-01)",
          icon: "🥪",
          startOffset: 12,
          duration: 12,
          status: "Pending",
          slaTargetMins: 12,
          criticalPath: false,
          digitalEvidence: "Catering truck in transit from commissary.",
          operator: "Catering Lead R. Naveen"
        },
        {
          id: "m6",
          code: "WATER_LAVATORY",
          name: "Potable Water & Lavatory Servicing",
          team: "Utility Crew",
          icon: "🚰",
          startOffset: 14,
          duration: 10,
          status: "Pending",
          slaTargetMins: 10,
          criticalPath: false,
          digitalEvidence: "Service truck scheduled for 14:38.",
          operator: "Utility Tech M. Joseph"
        },
        {
          id: "m7",
          code: "BAGGAGE_LOADING",
          name: "Outbound Baggage Loading & Trim Sheet",
          team: "Ramp Cargo Crew",
          icon: "📦",
          startOffset: 22,
          duration: 10,
          status: "Pending",
          slaTargetMins: 10,
          criticalPath: true,
          digitalEvidence: "130 bags sorted at makeup carousel.",
          operator: "Load Controller B. Vinoth"
        },
        {
          id: "m8",
          code: "BOARDING_PUSHBACK",
          name: "Pax Boarding, Doors Armed & Pushback",
          team: "Gate Team & Pushback Tug (TUG-03)",
          icon: "🛫",
          startOffset: 28,
          duration: 12,
          status: "Pending",
          slaTargetMins: 12,
          criticalPath: true,
          digitalEvidence: "Scheduled to commence boarding @ 14:52.",
          operator: "Gate Manager P. Saranya"
        }
      ]
    },

    {
      id: "FL-004",
      flightNo: "SG 304",
      airline: "SpiceJet",
      airlineCode: "SG",
      logoColor: "#ff0000",
      accentColor: "#e03131",
      aircraft: "Bombardier Q400",
      registration: "VT-SQC",
      paxCapacity: 78,
      paxInbound: 72,
      paxOutbound: 76,
      origin: "IXM (Madurai)",
      destination: "GOI (Goa)",
      gate: "G7",
      bayType: "Remote Stand (Apron Bay 7)",
      sta: "13:55",
      eta: "13:50",
      blockIn: "13:52",
      std: "14:30",
      targetTatMins: 30,
      elapsedMins: 28,
      status: "Pushback Ready",
      fuelRequiredKg: 1800,
      cargoBagsIn: 58,
      cargoBagsOut: 62,
      cateringMealTrays: 40,
      turnaroundHealth: "Optimal",
      delayReason: null,
      delayCode: null,
      milestones: [
        { id: "m1", code: "CHOCKS_DEBOARD", name: "Chocks & Deboard", status: "Completed", actualDuration: 4, icon: "🛬" },
        { id: "m2", code: "BAGGAGE_OFFLOAD", name: "Baggage Offload", status: "Completed", actualDuration: 6, icon: "🧳" },
        { id: "m3", code: "CABIN_CLEANING", name: "Cabin Cleaning", status: "Completed", actualDuration: 8, icon: "✨" },
        { id: "m4", code: "REFUELING", name: "Refueling", status: "Completed", actualDuration: 9, icon: "⛽" },
        { id: "m5", code: "CATERING", name: "Catering", status: "Completed", actualDuration: 6, icon: "🥪" },
        { id: "m6", code: "WATER_LAVATORY", name: "Water & Toilet", status: "Completed", actualDuration: 7, icon: "🚰" },
        { id: "m7", code: "BAGGAGE_LOADING", name: "Baggage Loading", status: "Completed", actualDuration: 7, icon: "📦" },
        { id: "m8", code: "BOARDING_PUSHBACK", name: "Boarding & Pushback", status: "Completed", actualDuration: 9, icon: "🛫" }
      ]
    }
  ],

  // Ground Support Equipment Fleet Matrix
  gseFleet: [
    { id: "TUG-01", type: "Towbarless Pushback Tug", model: "Trepel CHALLENGER 150", status: "Assigned (Gate G3)", batteryFuel: "85% Electric", lastMaint: "2026-09-15", assignedFlight: "6E 204" },
    { id: "TUG-02", type: "Heavy Pushback Tug", model: "Goldhofer AST-2", status: "Assigned (Gate G5)", batteryFuel: "92% Diesel", lastMaint: "2026-09-10", assignedFlight: "AI 508" },
    { id: "TUG-03", type: "Compact Ramp Tug", model: "TLD TMX-150", status: "Standby (Staging Bay 1)", batteryFuel: "78% Electric", lastMaint: "2026-09-18", assignedFlight: null },
    { id: "BL-01", type: "Electric Belt Loader", model: "TLD NBL-E", status: "Active (Gate G3 Fwd Hold)", batteryFuel: "90% Electric", lastMaint: "2026-09-12", assignedFlight: "6E 204" },
    { id: "BL-02", type: "Electric Belt Loader", model: "TLD NBL-E", status: "Active (Gate G3 Aft Hold)", batteryFuel: "82% Electric", lastMaint: "2026-09-12", assignedFlight: "6E 204" },
    { id: "BL-03", type: "Diesel Belt Loader", model: "Charlatte CBL-2000", status: "Active (Gate G2)", batteryFuel: "65% Diesel", lastMaint: "2026-09-08", assignedFlight: "QP 1102" },
    { id: "FB-01", type: "Aviation Fuel Bowser (20,000L)", model: "Tata-IOCL Refueler 40KL", status: "Active (Gate G3)", batteryFuel: "18,400 L ATF", lastMaint: "2026-09-20", assignedFlight: "6E 204" },
    { id: "FB-02", type: "Aviation Fuel Bowser (20,000L)", model: "Bharat Petroleum Refueler", status: "Standby (Fuel Farm)", batteryFuel: "19,200 L ATF", lastMaint: "2026-09-19", assignedFlight: null },
    { id: "CAT-01", type: "Catering Highloader", model: "Mallaghan CT-6000", status: "Active (Gate G3)", batteryFuel: "70% Diesel", lastMaint: "2026-09-14", assignedFlight: "6E 204" },
    { id: "CAT-02", type: "Catering Highloader", model: "Mallaghan CT-6000", status: "Maintenance Warning", batteryFuel: "45% Diesel", lastMaint: "2026-09-02", assignedFlight: "AI 508" },
    { id: "GPU-01", type: "Ground Power Unit (90kVA 400Hz)", model: "Hobart JetEx 4", status: "Connected (Gate G3)", batteryFuel: "95% Grid-Power", lastMaint: "2026-09-16", assignedFlight: "6E 204" },
    { id: "GPU-02", type: "Ground Power Unit (90kVA 400Hz)", model: "Hobart JetEx 4", status: "Connected (Gate G5)", batteryFuel: "90% Grid-Power", lastMaint: "2026-09-16", assignedFlight: "AI 508" }
  ],

  // IATA Standard Delay Attribution Matrix (AHM 730 / 780)
  iataDelayCodes: [
    { code: "31", category: "Aircraft Cleaning", description: "Late or inadequate cabin cleaning", standardMinAllowance: 12 },
    { code: "32", category: "Loading & Unloading", description: "Baggage / Cargo handling staff or conveyor belt equipment shortage", standardMinAllowance: 10 },
    { code: "33", category: "Ramp Handling", description: "Delay in ground power connection, potable water, or pushback tug", standardMinAllowance: 8 },
    { code: "34", category: "Catering", description: "Late delivery of catering carts or highloader breakdown", standardMinAllowance: 12 },
    { code: "35", category: "Refueling", description: "Late fueling bowser arrival or defueling / density test verification hold", standardMinAllowance: 14 },
    { code: "41", category: "Aircraft Defects", description: "Minor technical discrepancy or maintenance logbook sign-off delay", standardMinAllowance: 15 },
    { code: "61", category: "Air Traffic Control", description: "ATC en-route congestion, slot revision, or departure sequencing delay", standardMinAllowance: 0 },
    { code: "81", category: "Passenger & Gate", description: "Concourse security congestion or late gate boarding closure", standardMinAllowance: 10 }
  ],

  // Aviation Business ROI & Financial Constants (Industry Standard Benchmarks)
  roiBenchmarks: {
    delayPenaltyPerMinINR: 10500, // ₹10,500/min estimated direct cost of delay in Indian commercial aviation
    fuelAuxiliaryBurnKgPerMin: 1.8, // APU fuel burn kg/min while idling at gate
    fuelCostPerKgINR: 110, // ATF approx cost/kg
    co2KgPerKgFuel: 3.16, // kg CO2 emitted per kg ATF burned
    fleetDailyFlightsDefault: 40,
    averageMinutesSavedPerTAT: 4.5
  },

  // Presentation Pitch Deck Slides for Hackathon Juries
  pitchSlides: [
    {
      slideNo: 1,
      title: "The Multimillion-Dollar Problem in Aviation",
      subtitle: "Turnaround Time (TAT) Bottleneck & Ground Operations Chaos",
      points: [
        "Every single minute an aircraft sits idle at the gate costs airlines **₹10,500+ ($125)** in direct loss.",
        "A 35-minute aircraft turnaround requires **12 independent ground agencies** (Fuel, Baggage, Cabin Cleaners, Catering, Boarding Gate, Pushback Tug).",
        "Today, 85% of regional airports still rely on **manual walkie-talkies, physical paper fuel slips, and handwritten ramp logs**.",
        "A single 3-minute delay in catering highloader or fuel slip sign-off cascades into missed ATC slots, passenger compensation, and severe schedule disruptions."
      ],
      badge: "PROBLEM & VALIDATION"
    },
    {
      slideNo: 2,
      title: "Introducing AeroFlow 360",
      subtitle: "Autonomous Aircraft Turnaround & Smart Ramp Orchestration Matrix",
      points: [
        "**Real-Time Critical Path Engine**: Automatically calculates the dynamic 8-milestone Gantt timeline the instant the aircraft lands.",
        "**Single-Tap Digital Ground Handshake**: Ground crews (Fuel, Ramp, Cabin, Cargo) tap verified milestones with zero voice call delays.",
        "**Predictive SLA Escalation System**: Triggers instant visual/audio alerts to Airport Duty Managers if any milestone deviates by >120 seconds.",
        "**Automated Ground Support Equipment (GSE) Allocator**: Eliminates idle equipment travel time by auto-dispatching nearest pushback tugs and belt loaders."
      ],
      badge: "THE AUTOMATED SOLUTION"
    },
    {
      slideNo: 3,
      title: "The BBA Aviation Management Edge",
      subtitle: "Lean Six Sigma & DMAIC Framework Applied to Airport Operations",
      points: [
        "**Define**: Target 35-minute standard turnaround for narrow-body aircraft (A320/B737) with zero preventable ground delays.",
        "**Measure**: Track 8 granular milestone timestamps down to the second with digital operator accountability.",
        "**Analyze**: Automatically map root causes directly to **IATA AHM 730/780 Delay Codes** to eliminate inter-agency dispute.",
        "**Improve**: Parallelize independent workflows (Refueling + Catering + Cabin Grooming) on a synchronized digital timeline.",
        "**Control**: Live AOCC executive dashboard and digital IATA clearance certificate generation."
      ],
      badge: "MANAGEMENT METHODOLOGY"
    },
    {
      slideNo: 4,
      title: "Business Impact, ROI & Carbon Reduction",
      subtitle: "Quantifiable Financial & Environmental Value for Airlines & Airports",
      points: [
        "**₹6.88 Crores ($825,000) Annual Savings** for an airline operating 40 daily turns by saving just 4.5 minutes per turnaround.",
        "**236,520 Liters of Aviation Turbine Fuel (ATF)** saved annually by shortening Ground Power Unit (GPU) and APU idle runtimes.",
        "**747 Metric Tonnes of CO2 Emissions Avoided** per year, directly supporting ICAO Green Airport and ESG compliance goals.",
        "**Zero Paper Waste**: 100% digital fuel chits, load-and-trim sheets, and ramp handover certificates."
      ],
      badge: "FINANCIAL ROI & ESG"
    },
    {
      slideNo: 5,
      title: "Implementation Roadmap & Future Scalability",
      subtitle: "From Regional Indian Airports to Global Smart Hubs",
      points: [
        "**Phase 1 (Immediate)**: Cloud web dashboard for AOCC + mobile Progressive Web App (PWA) for ramp ground handlers.",
        "**Phase 2 (IoT & Computer Vision)**: AI CCTV camera stream integration for automatic chocks-on and baggage-belt detection.",
        "**Phase 3 (Enterprise Integration)**: Direct API synchronization with Airline Departure Control Systems (DCS), SITA, and AFTN Flight Plans."
      ],
      badge: "SCALABILITY & FUTURE"
    }
  ]
};
